"""Measure residual signals in a free DAG versus an observed-boundary query.

This is an untrained mathematical diagnostic, not a learning or advantage test.
All queries are pure; full-graph qualification is checked and reported. The
observed boundary is generated by a fixed synthetic body, not a future label.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import statistics
from pathlib import Path

import cadence
from cadence import Cortex

SEEDS = (2, 7, 11, 19, 29)
PRIORS = (0.1, 0.01, 0.001, 0.0001)
HISTORIES = ((-0.8, -0.4), (-0.8, 0.4), (0.8, -0.4), (0.8, 0.4))


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def save(path, value):
    with path.open("x") as handle:
        json.dump(value, handle, indent=2, allow_nan=False)
        handle.write("\n")


def brain(seed, prior):
    cortex = Cortex(
        seed=seed,
        state_prior=prior,
        tolerance=1e-10,
        settle_budget=4096,
    )
    history = cortex.input("history", shape=2)
    predicted = cortex.column("predicted_observation", patches=2, inputs=history)
    reflection = cortex.observer("reflection", patches=2, observes=predicted)
    cortex.output("observed", shape=2, reads=predicted)
    cortex.output("answer", shape=2, reads=reflection)
    return cortex.build()


def run(output):
    output.mkdir(exist_ok=False, parents=True)
    package = Path(cadence.__file__).resolve().parent
    protocol = {
        "scope": "Untrained signal diagnostic; no task accuracy or efficiency advantage claim",
        "seeds": SEEDS,
        "state_priors": PRIORS,
        "histories": HISTORIES,
        "observed_body": "y0=.7*x0-.2*x1; y1=.2*x0+.6*x1",
        "conditions": ["all_states_free", "past_observation_clamped"],
        "tolerance": 1e-10,
        "budget": 4096,
        "collector_sha256": sha(Path(__file__)),
        "sources": {
            p.relative_to(package).as_posix(): sha(p) for p in package.rglob("*.py")
        },
        "mechanism_hypothesis": "Residuals in a free acyclic graph approach zero as state prior approaches zero; an observed mismatch can retain a large residual at fixed parameters.",
    }
    save(output / "protocol.json", protocol)
    rows = []
    for seed in SEEDS:
        founder = None
        for prior in PRIORS:
            model = brain(seed, prior)
            parameters = (model.weights, model.biases)
            if founder is None:
                founder = parameters
            assert parameters == founder
            before = model.snapshot()
            for history in HISTORIES:
                measured = [
                    0.7 * history[0] - 0.2 * history[1],
                    0.2 * history[0] + 0.6 * history[1],
                ]
                for condition in protocol["conditions"]:
                    target = (
                        None
                        if condition == "all_states_free"
                        else {"observed": measured}
                    )
                    result = model.settle({"history": history}, targets=target)
                    assert model.snapshot() == before
                    contributions = [
                        math.fsum(
                            w * result["errors"][source]
                            for (kind, source, destination), w in zip(
                                model.graph.edges, model.weights, strict=True
                            )
                            if kind == "residual" and destination == patch
                        )
                        for patch in (2, 3)
                    ]
                    rows.append(
                        {
                            "seed": seed,
                            "state_prior": prior,
                            "history": history,
                            "condition": condition,
                            "actual_past": measured,
                            "qualified": result["qualified"],
                            "reason": result["reason"],
                            "stationarity": result["stationarity"],
                            "work": result["work"],
                            "state": result["state"],
                            "errors": result["errors"],
                            "predictions": result["predictions"],
                            "observed_error_rms": math.sqrt(
                                sum(e * e for e in result["errors"][:2]) / 2
                            ),
                            "residual_activation_rms": math.sqrt(
                                sum(z * z for z in contributions) / 2
                            ),
                            "snapshot_pure": True,
                        }
                    )
    groups = []
    for prior in PRIORS:
        for condition in protocol["conditions"]:
            group = [
                r
                for r in rows
                if r["state_prior"] == prior and r["condition"] == condition
            ]
            qualified = [r for r in group if r["qualified"]]
            groups.append(
                {
                    "state_prior": prior,
                    "condition": condition,
                    "queries": len(group),
                    "qualified": sum(r["qualified"] for r in group),
                    "median_observed_error_rms_qualified": statistics.median(
                        r["observed_error_rms"] for r in qualified
                    )
                    if qualified
                    else None,
                    "median_residual_activation_rms_qualified": statistics.median(
                        r["residual_activation_rms"] for r in qualified
                    )
                    if qualified
                    else None,
                }
            )
    save(
        output / "result.json",
        {
            "protocol_sha256": sha(output / "protocol.json"),
            "sources_unchanged": protocol["sources"]
            == {
                p.relative_to(package).as_posix(): sha(p) for p in package.rglob("*.py")
            }
            and protocol["collector_sha256"] == sha(Path(__file__)),
            "all_queries_qualified": all(r["qualified"] for r in rows),
            "groups": groups,
            "rows": rows,
        },
    )
    print(json.dumps(groups, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    run(parser.parse_args().out)
